name: Publish on push
# branch name in Git becomes tag name in Docker Hub
# subseqent pushes to branch overwrites previous Docker tag

on:
  push:
    branches: '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Extract tag name
      env:
        REF_PATH: ${{ github.ref }}
      shell: bash
      run: echo "##[set-output name=ref;]$(echo ${REF_PATH#refs/*/})"
      id: extract_ref
    - name: Extract version
      env:
        REF: ${{ steps.extract_ref.outputs.ref }}
      shell: bash
      run: echo "##[set-output name=ver;]$(echo ${REF%%-*})"
      id: extract_version
    - name: Extract target triplet
      env:
        REF: ${{ steps.extract_ref.outputs.ref }}
      shell: bash
      run: echo "##[set-output name=target;]$(echo ${REF#*-})"
      id: extract_target
    - name: Build the Docker image
      env:
        DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      run: |
        export HISTFILE=
        echo "${DOCKER_ACCESS_TOKEN}" | docker login -u ccfactory --password-stdin
        docker build . --file Dockerfile --tag ${{ github.repository }} \
          --build-arg BINUTILS_VER=${{ steps.extract_version.outputs.ver }} \
          --build-arg TARGET=${{ steps.extract_target.outputs.target }}
        docker logout
    - name: Push to Docker Hub
      env:
        DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      run: |
        # dunno if useful, but why not to erase it?
        export HISTFILE=
        echo "${DOCKER_ACCESS_TOKEN}" | docker login -u ccfactory --password-stdin
        docker tag ${{ github.repository }} ccfactory/${{ github.repository }}:${{ steps.extract_ref.outputs.ref }}
        docker push ccfactory/${{ github.repository }}:${{ steps.extract_ref.outputs.ref }}
        docker logout
